
// System Design is the process of defining the architecture, components, interfaces, and data flow of a software system so that it meets functional requirements (what it should do) and non-functional requirements (scale, performance, reliability, security).

// An Operating System is system software that manages hardware resources, provides services to application programs, and ensures efficient, fair, and secure execution of programs.

// a program is an executable file 

// a process is a program in execution 

// a thread is the smallest unit of execution with in a process , sharing memory and resources with other threads of the same process

// Multitasking is the ability of an OS to execute multiple processes concurrently by rapidly switching the CPU among them.

// Multithreading is the execution of multiple threads within a single process to improve performance and responsiveness.

// Context switching is the process of saving the state of a running process or thread and restoring the state of another so execution can resume correctly.

// Too many threads/processes =
// ❌ more context switches = ❌ slower system

// The kernel is the core component of the OS that and directly manages CPU, memory, devices, and system calls.

// User space is the memory area where application programs execute with restricted access to system resources.

// A system call is an interface through which a user program requests services from the kernel.

//Memory Management is the function of an operating system that controls the allocation, deallocation, protection, and mapping of main memory so that multiple processes can execute efficiently and safely.

// memory management directly impacts the performance scalability and reliability

// A logical address is an address generated by the CPU during program execution that does not directly correspond to a physical memory location.

// A physical address is the actual location in RAM accessed by memory hardware.

// The Memory Management Unit (MMU) is a hardware component that performs runtime translation of logical addresses into physical addresses.

// MMU enables virtual memory , protections , paging 

// Swapping is the process of temporarily moving a process from main memory to secondary storage to free up memory for other processes. swapping helps to run more processes than RAM allows and avoids system crashes 

// FCFS schedules processes in the order they arrive in the ready queue.
// convoy effect occurs in fcfs because one slow process blocks many fast processes.

// sjf => minimum average waiting time 

// priority scheduling => Priority scheduling assigns CPU to processes based on priority values.

// Round Robin is a preemptive scheduling algorithm where each process is given a fixed time quantum in cyclic order.
// king , best , no starvation , best for time-sharing systems 

// Concurrency is the ability of a system to handle multiple execution paths that overlap in time.

// A race condition occurs when multiple threads access shared data concurrently and the final outcome depends on execution order.

// Synchronization ensures controlled access to shared resources so that concurrent execution does not lead to incorrect results.

// A deadlock is a situation where two or more processes are permanently blocked, each waiting for resources held by others

// Virtual Memory is a memory management technique that gives processes the illusion of a large, contiguous memory space by storing only required portions of a process in main memory while the rest resides on secondary storage.

// with virtual memory , programs can be larger than the RAM , better multiprogramming , isolation and protection 

// Concept	Meaning
// Page	Fixed-size block of logical memory
// Frame	Fixed-size block of physical memory
// Page Table	Mapping from page → frame

// Paging => instead of one big book , tear the book into equal pages and then put some pages on the table and remaining on the shelf . os moves pages not the books 

// paging => no external fragmentation , easy memory allocation , efficient swapping 

// Page Table => page table is a map => It tells which page is currently sitting on that desk 

// page table is a data structure maintained by the os that maps the virtual page numbers to physical frame numbers

// page table stores frame number , valid or invalid bit , protection bits , dirty bit , reference bit

// TLB -> translation lookaside buffer --> a transition lookaside buffer (TLB) is a small , fast cache that stores recent virtual-to-physical address translations to reduce memory access time 

// with TLB --> fast address translation and high performance 

// Page Fault --> a page fault occurs when a process accesses a page that is not currently present in the memory 

// page fault handling steps --> update page table 

// Page replacement  ==> when the table is full , to bring a new page we must remove the old page 

// page replacement is the process of selecting a page in memory to be swapped out when a new page needs to be loaded and no free frames are available

// goal is to minimize the pagefaults , maximize the performance 

// PAGE REPLACEMENT ALGORITHMS 

// FIFO --> oldest page goes out --> fifo replaces the page that has been in the memory for long time 

// problem is with FIFO is beladly anomoly

// LRU -> least recently used -> remove page that has not been accessed for the longest time 
// very good performance , approximates the optimal 

// OPTIMAL (Theoritical)
// remove page that wont be used in the future 
// optimal replaces the page that will not be used for the longest time in the future

// Trashing -> (system killer) -> you keep running => table->shelf->tabale->shelf

// Trashing occurs when a system spends more time handling page faults than executing the actual instructions

// causes for the trashing => too many processes , too little memory , poor page replacement 













// Questions 

What is the difference between low-level design and system design?
Why is system design more about trade-offs than correctness?
Can a system be correct but badly designed? (YES)
Why can’t applications directly access hardware?
What problems occur if there is no OS?
How does OS help in fairness and isolation?
Why are threads called lightweight processes?
Can two processes share memory?
Why are threads faster than processes?
Is multithreading always faster?
Does multithreading help on a single CPU?
Why do web servers prefer threads?
Why is kernel mode dangerous?
What happens if kernel crashes?
Why can’t apps access hardware directly?
Why is memory management required in multiprogramming?
What happens if memory is not protected?
Can two processes share the same memory?
Who generates logical addresses?
Who converts logical to physical?
Why can’t programs use physical addresses directly?
Why is scheduling needed?
What happens if scheduling is unfair?
Is fairness always good?
What is ageing?
Can priority scheduling cause deadlock?
Preemptive vs non-preemptive?
What happens if time quantum is too small?
Why RR is used in OS?
Difference between RR and FCFS?
Difference between concurrency and parallelism?
Why concurrency is hard?
Can concurrency exist on single CPU?
Why race conditions are dangerous?
Can race condition exist without threads?
How do you detect race conditions?
Can deadlock be prevented?
Difference between deadlock and starvation?
Which condition is easiest to break?
Can a program be larger than RAM?
Why virtual memory improves CPU utilization?
Is virtual memory implemented in hardware or software?
Why round robin may fail in real systems?
What is sticky session?
Which algorithm for long-lived connections?
Is load balancer a SPOF?
How do you fix SPOF?
What is active-active vs active-passive?
Why page size is fixed?
Difference between paging and segmentation?
What happens if page table is huge?
Where is page table stored?
Why page table lookup is slow?
What is a valid/invalid bit?
What happens on TLB miss?
Is TLB hardware or software?
Why TLB size is small?
Is page fault an error?
Difference between minor and major page fault?
Can page fault be handled in user space?
What is Belady’s anomaly?
Why LRU is better than FIFO?
Can FIFO show anomalies?
Why Optimal is not practical?
Can class diagram show private/public?
Difference between class and object diagram?
Should business logic appear here?
Does association imply ownership? (NO)
Can association be one-way?
What is multiplicity?
What UML is
Structural vs behavioral diagrams
Class diagram purpose
Association vs aggregation vs composition
When to use sequence diagrams
Does SRP mean one method per class? (NO)
What is “reason to change”?
Give a real SRP violation example
How does OCP reduce bugs?
Is OCP possible without interfaces?
Strategy pattern relates to which principle?
Why LSP is about behavior, not syntax?
Can compilation succeed but LSP still fail? (YES)
Give real-world LSP violation.
Difference between DI and DIP?
How DIP helps unit testing?
Can DIP exist without interfaces?

















































































// Load balancer -->  like a gate keeper => tells you go there , you go there ..

// A Load Balancer is a component that distributes incoming client requests across multiple backend servers to ensure high availability, scalability, and efficient resource utilization.
// with load balancer => horizontal scaling , fault tolerance
// when traffic increases => Add more servers + load balancer

// algorithms for load balancing => 1) round robin=> every one gets turn 2) least connections => servers with fewst active connections  3)hash method
// L4 Load Balancer --> looks at address on the envelope --> Operates at transport layer (TCP/UDP) and routes traffic based on IP and port.
// L7 Load Balancer --> reads letter inside --> Operates at application layer and routes traffic based on URL, headers, cookies, etc.

// A Single Point of Failure (SPOF) is a component whose failure brings down the entire system => solution is multiple load balancers , health checks.

// HIGH LEVEL DESIGN 

// High Level Design (HLD) is the architectural design of a system that defines its major components, data flow and scalability strategies, without going into implementation details.

// | Aspect      | HLD                      | LLD              |
// | ----------- | ------------------------ | ---------------- |
// | Focus       | Architecture             | Implementation   |
// | Level       | System-wide              | Component-level  |
// | Talks about | Services, DB, Cache      | Classes, methods |
// | Asked in    | System Design interviews | Coding rounds    |

// every high level design uses these blocks
// 1️⃣ Client
// 2️⃣ Load Balancer
// 3️⃣ Application Servers
// 4️⃣ Cache
// 5️⃣ Database
// 6️⃣ Message Queue (sometimes)
// 7️⃣ Storage (files/media)
// 8️⃣ Monitoring & Logging


// Question: Design a URL Shortener (HLD)
// Answer Structure:
// Requirements (short URLs, redirect)
// Scale (100M URLs)
// Architecture (LB → Servers → Cache → DB)
// DB choice (NoSQL for fast lookup)
// Cache (URL → original mapping)
// Scalability (hash-based sharding)
// Reliability (replicas, backup)


// UML ==> UML is drawing pictures so humans understand software -> unified modeling language is a standardized visual language used to represent the structure of and behavior of a software system 
// UML => clarity of thought => UML answers what and why? like what is the system made of and how the system behaves over time 

// CLASS DIAGRAM ==> class diagram is a blueprint before building a house , you draw rooms 

// class diagram is a structured uml diagram that represents the classes , their attributes , methods and relationships between them.

// What Interviewers Expect
// When they ask:
// “Draw a class diagram”
// They want:
// Correct relationships
// Clear responsibilities
// No overengineering

// A class box has 3 parts:
// Class name
// Attributes (data)
// Methods (behavior)


// ASSOCIATION ==> an association is a relationship between two classes indicating that objects of one class can interact with the objects of another 

// Aggregation ==> aggregation is a special form of association that represents a whole-part relationship , where the part can exist independently of the whole 

// Aggregation = weak ownership


// SOLID PRINCIPLES 

// solid is a set of five object-oriented design principles that help developers create sustainable , maintanable , flexible and scalable software by reducing tight coupling and increasing the clarity of responsibility 

// 1) S ------------->SRP (single responsibility principle)
// one person -> one job 
// if one process does everything --> mess
// def: -> a class should have only one reason to change , meaning it should have only one responsibility
// when one class does logging , validation and everything => a small change breaks everything 

// 2) O ------------->OCP (open / closed principle)
// you should be able to add new features without breaking the old toys 
// software entities should be open for extension but not for modification 


// 3) Liskov substitution principle 
// if something looks like a bird then it should behave like a bird 
// def:objects of superclass should be replaceable with objects of its subclasses without breaking the correctness of the program.
// bad                                            good 
// Bird                                           flying bird extends bird 
// - fly()                                        penguin extends bird
// Penguin extends Bird


// 4) ISP --> interface segregation principle (ISP)
// dont force someone to do things they dont need
// def: no client should be forced to depend on the methods it does not use 
// big interfaces causes dummy methods , empty implementations 

// bad design        Good design 
// Worker           workable
// - work()           eatable 
// - eat()             sleepable 
// - sleep()


// Robot implements Worker:
// eat() ❌
// sleep() ❌

// 5) D ---> Dependency Inversion Principle(DIP)
// dont depend on details depend on ideas
// High level modules should not depend on the low level modules , both should depend on the abstractions 
// without dip code is tightly coupled , hard to rest and hard to replace components 

// | Principle | One-liner                      |
// | --------- | ------------------------------ |
// | SRP       | One class, one job             |
// | OCP       | Add without modifying          |
// | LSP       | Subclass must behave correctly |
// | ISP       | Small, focused interfaces      |
// | DIP       | Depend on abstractions         |










// System Design 1: Design Tiny URL (with Advanced Design)/ URL Shortner / Bitly / TinyURL / HLD/ LLD

// step-1
// Functional requirements 
// --> create a short url from a long url 
// optional : ==> support system url 
// optional : ==> support expiration date 
// user should get redirected to the original url from the short url 

// step-2
// Non-Functional requirements
// --> low latency (url-creating , on redirect ~200ms)
// --> scale:100M DAU/1B url
// --> shorten url should be unnique 
// --> CAP => availabillity >> consistency (eventual)

// step-3  --> Identifying entity
// short-url
// long -url
// user 


// API creation 

// POST:/v1/url -> short-url
// {
//     longURL,
//     customURL,
//     expirationDate?
// }

// GET:/v1/url/{shortURL}->longURL

// HIGH LEVEL DESIGN



// LOW LEVEL DESIGN 

// encryption logic --> shal1(long URL) --> (shortURL:6,7) --> response
// Counter 
// as there are many users , a single server cannot manage the huge load so we should use horizontal scaling or vertical scaling for to resolve this issue and here horizontal scaling is best because maintaining 100M users is very hard and it is best to use horizontal scaling 



// zookeeper

// zookeeper is a distributed , open-source coordination service for distributed applications , provding centralized services for configuration management , naming , synchronization and group services , making it easier to manage large clusters 
// used for: maintaining configuration information , naming , providing distributed synchronization , distributed locking , group service etc.





























